

service: tello
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
functions:
  hello:
    handler: handler.hello
    environment:
      SAMPLE_ENV_VAR: ${param:sampleEnvVar, 'default value'}
    events:
      - httpApi:
          path: /tello
          method: get  
package:
  artifact: ${param:artifact}       
#plugins:
#  - serverless-deployment-bucket@latest
